import type { Student, RevenueData } from "./types";

export const students: Student[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    avatar: "https://picsum.photos/seed/avatar1/100/100",
    plan: "Intermediate",
    registrationDate: "2023-01-15",
    status: "Active",
    paymentStatus: "Paid",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    avatar: "https://picsum.photos/seed/avatar2/100/100",
    plan: "Advanced",
    registrationDate: "2022-11-20",
    status: "Active",
    paymentStatus: "Overdue",
    dueDate: "2024-05-10",
  },
  {
    id: "3",
    name: "Michael Johnson",
    email: "michael.j@example.com",
    avatar: "https://picsum.photos/seed/avatar3/100/100",
    plan: "Basic",
    registrationDate: "2023-03-01",
    status: "Active",
    paymentStatus: "Paid",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.d@example.com",
    avatar: "https://picsum.photos/seed/avatar4/100/100",
    plan: "Intermediate",
    registrationDate: "2023-09-10",
    status: "Inactive",
    paymentStatus: "Paid",
  },
  {
    id: "5",
    name: "David Wilson",
    email: "david.w@example.com",
    avatar: "https://picsum.photos/seed/avatar5/100/100",
    plan: "Advanced",
    registrationDate: "2021-07-22",
    status: "Active",
    paymentStatus: "Overdue",
    dueDate: "2024-05-01",
  },
  {
    id: "6",
    name: "Sarah Brown",
    email: "sarah.b@example.com",
    avatar: "https://picsum.photos/seed/avatar6/100/100",
    plan: "Basic",
    registrationDate: "2024-04-05",
    status: "Pending",
    paymentStatus: "Pending",
  },
];

export const revenueData: RevenueData[] = [
    { month: "Jan", revenue: 2380 },
    { month: "Feb", revenue: 2100 },
    { month: "Mar", revenue: 2550 },
    { month: "Apr", revenue: 2400 },
    { month: "May", revenue: 2890 },
    { month: "Jun", revenue: 2650 },
];
